name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
      # 检出代码

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm' # 这可以帮助缓存 pnpm 的存储器

    - name: Install pnpm
      run: npm install -g pnpm
      # 安装 pnpm

    - name: Install dependencies
      run: pnpm install
      # 安装项目依赖

    - name: BUILD
      run: pnpm build
      # 运行测试脚本
